### ISSUE TITLE
Create/Update with Location Data fails

### ISSUE THREAD

**Issue by lynchd** [intercom/intercom-ruby#129]
- Gem Version: intercom (2.4.1)
- Ruby Version : ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-linux]
## Use Case

Migration of data from MixPanel to Intercom
## Expected Behaviour

Record is updated mapping MixPanel [city, timezone, region] to intercom equivalents. Or in the basic case, the Location Object for that user is updated. 
## Actual Behaviour

When location_data is offered by means of Intercom::User.create(.. :location_data => { .. } ..) request  fails with 

```
usr/local/share/ruby/gems/2.0/gems/intercom-2.4.1/lib/intercom/request.rb:137:in `raise_application_errors_on_failure': bad 'location_data' parameter (Intercom::BadRequestError)
    from /usr/local/share/ruby/gems/2.0/gems/intercom-2.4.1/lib/intercom/request.rb:90:in `parse_body'
    from /usr/local/share/ruby/gems/2.0/gems/intercom-2.4.1/lib/intercom/request.rb:66:in `block in execute'
    from /usr/share/ruby/2.0/net/http.rb:852:in `start'
    from /usr/local/share/ruby/gems/2.0/gems/intercom-2.4.1/lib/intercom/request.rb:61:in `execute'
    from /usr/local/share/ruby/gems/2.0/gems/intercom-2.4.1/lib/intercom.rb:95:in `send_request_to_path'
    from /usr/local/share/ruby/gems/2.0/gems/intercom-2.4.1/lib/intercom.rb:124:in `post'
    from /usr/local/share/ruby/gems/2.0/gems/intercom-2.4.1/lib/intercom/api_operations/save.rb:24:in `save'
    from /usr/local/share/ruby/gems/2.0/gems/intercom-2.4.1/lib/intercom/api_operations/save.rb:11:in `create'
    from import-intercom.rb:21:in `block in <main>'
    from import-intercom.rb:18:in `each'
    from import-intercom.rb:18:in `<main>'
```
## Sample Code

```
user = Intercom::User.create(
                :email => properties["$email"],
                :name => "#{properties["$first_name"]} #{properties["$middle_name"]} #{properties["$last_name"]}",
                :user_id => record["$distinct_id"],
                :created_at => t_parse(properties["Signed Up"]),
                :remote_created_at => t_parse(properties["Signed Up"]),
                :location_data => {
                   # :timezone => properties["$timezone"],
                   # :region_name => properties["$region"],
                   #  :city_name => properties["$city"],
                   :city_name => 'Dublin',
                   :region_name => 'Leinster'
                },
                :last_request_at => t_parse(properties["$last_seen"]),
                :custom_attributes => {
                   :gender => properties["Gender"],
                   :date_of_birth => t_parse(properties["Date Of Birth"]),
                   :location => properties["Location"],
                   :client_os => properties["Client OS"],
                   :client_language => properties["Client Language"],
                   :device => properties["Client Device"],
                   :followers => properties["Followers"],
                   :following => properties["Following"],
                   :connected_native => properties["Connected Native"],
                   :connected_spotify => properties["Connected Spotify"],
                   :connected_youtube => properties["Connected Rdio"],
                   :connected_desktop => properties["Connected Desktop"],
                   :connected_pandora => properties["Connected Pandora"],
                   :connected_deezer => properties["Connected Deezer"],
                   :connected_8tracks => properties["Connected 8Tracks"],
                   :connected_soundcloud => properties["Connected Soundcloud"],
                   :connected_rdio => properties["Connected Rdio"],
                   :google_linked => properties["Linked Google"],
                   :twitter_linked => properties["Linked To Twitter"],
                   :facebook_linked => properties["Linked Facebook"],
                   :facebook_token_valid => properties["Facebook Token Valid"]
                }
    )
```
## Sample User

I'm trying to execute a create/update on https://app.intercom.io/apps/gkrv0mwf/users/54634f155df18a53a5000a81 as an example

Interesting to note that if I remove the location data parameter, the create/update works.

**Comment by sozidatel** [comment]
> Throwing an 'operation unsupported' style exception definitely would have saved me some time.

:+1:

**Comment by ebuildy** [comment]
Hello, is it still the case ?

Because I can read on documentation that it should work:

https://developers.intercom.io/docs/user-model

I send "location_data" object and nothing seems to be saved :/

**Comment by bartocc** [comment]
+1

I also have the problem with

```ruby
user.locationData = {:region_name => "MI"}
intercom.users.save(user)
```

or 

```ruby
user.location_data = {:region_name => "MI"}
intercom.users.save(user)
```

**Comment by sdogruyol** [comment]
Up 👍
