### ISSUE TITLE
Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: Unauthorized token and http_code: '401'. Please contact Intercom with these details.

### ISSUE THREAD

**Issue by th3james** [intercom/intercom-ruby#145]
I'm getting the above error when trying to send any commands to Intercom from my Rails console. I've configured a test app on Intercom, (which `intercom-rails` successfully posts to), but for some reason, `intercom-ruby` isn't working.

```ruby
irb(main):009:0> Intercom::User.all.map {|user| user.email }

Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: Unauthorized token and http_code: '401'. Please contact Intercom with these details.
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/intercom-2.4.4/lib/intercom/request.rb:148:in `raise_application_errors_on_failure'
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/intercom-2.4.4/lib/intercom/request.rb:90:in `parse_body'
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/intercom-2.4.4/lib/intercom/request.rb:66:in `block in execute'
	from ~/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/intercom-2.4.4/lib/intercom/request.rb:61:in `execute'
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/intercom-2.4.4/lib/intercom.rb:95:in `send_request_to_path'
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/intercom-2.4.4/lib/intercom.rb:136:in `get'
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/intercom-2.4.4/lib/intercom/collection_proxy.rb:22:in `block in each'
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/intercom-2.4.4/lib/intercom/collection_proxy.rb:18:in `loop'
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/intercom-2.4.4/lib/intercom/collection_proxy.rb:18:in `each'
	from (irb):9:in `map'
	from (irb):9
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands/console.rb:90:in `start'
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands/console.rb:9:in `start'
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:69:in `console'
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'irb(main):010:0>
```
The error implies an authentication error, but `Intercom.app_id` & `Intercom.app_api_key` are both set correctly using same details as `IntercomRails` (which is reporting users correctly).
```ruby
irb(main):009:0> IntercomRails::Config.api_key == Intercom.app_api_key
=> true
irb(main):010:0> IntercomRails::Config.app_id == Intercom.app_id
=> true
```

**Comment by josler** [comment]
Hi @th3james,

Are you using an API Key from here: http://app.intercom.io/apps/api_keys to configure your Ruby client? To point at the test app you should use an API Key from your test app's settings page.

If you're still having trouble, could you contact me through Intercom with your App ID and I can take a closer look.

Thanks!

**Comment by ngelx** [comment]
I've got the same problem under the test app. If credential are change to production ones, all works as expected. So I think that the problems comes with test credential pair. How is that IntercomRails work with wrong test credential pair? I've got no idea. :)

**Comment by th3james** [comment]
@ngelx My problem was down to the fact that I hadn't realised that the API key differed per app (production vs. test). I had assumed the API key was the same for both. Once I got the API key for my test application, it worked fine.
