### ISSUE TITLE
better error handling for bad values

### ISSUE THREAD

**Issue by milesmatthias** [intercom/intercom-ruby#221]
When updating a lead through the API I get this error if I use a nil value:

```
Intercom::BadRequestError: Value:  not of type Numeric, String or Boolean
        from /var/www/equityeats.com/shared/bundle/ruby/2.1.0/gems/intercom-3.3.0/lib/intercom/request.rb:140:in `raise_application_errors_on_failure'
        from /var/www/equityeats.com/shared/bundle/ruby/2.1.0/gems/intercom-3.3.0/lib/intercom/request.rb:94:in `parse_body'
        from /var/www/equityeats.com/shared/bundle/ruby/2.1.0/gems/intercom-3.3.0/lib/intercom/request.rb:70:in `block in execute'
        from /home/ubuntu/.rbenv/versions/2.1.4/lib/ruby/2.1.0/net/http.rb:853:in `start'
        from /var/www/equityeats.com/shared/bundle/ruby/2.1.0/gems/intercom-3.3.0/lib/intercom/request.rb:65:in `execute'
        from /var/www/equityeats.com/shared/bundle/ruby/2.1.0/gems/intercom-3.3.0/lib/intercom/client.rb:94:in `execute_request'
        from /var/www/equityeats.com/shared/bundle/ruby/2.1.0/gems/intercom-3.3.0/lib/intercom/client.rb:84:in `put'
        from /var/www/equityeats.com/shared/bundle/ruby/2.1.0/gems/intercom-3.3.0/lib/intercom/api_operations/save.rb:24:in `save'
```

which really doesn't tell me anything.

Ideally I'd like to see:

* the class of the value I'm sending (nil, etc.)
* the key for the bad value
* the endpoint I'm using here (this script in particular does things with both users & leads)

**Comment by aivanov93** [comment]
Same problem!

**Comment by Skaelv** [comment]
I'm closing this issue as it duplicate https://github.com/intercom/intercom-ruby/issues/200
We'll come back to you once we have more informations about this issue.
