### ISSUE TITLE
Intercom::ResourceNotFound: User Not Found (when creating user)

### ISSUE THREAD

**Issue by andrewhavens** [intercom/intercom-ruby#469]
## Version info
  - intercom-ruby version: 3.7.6
  - Ruby version: 2.5.5

## Expected behavior
Creating a user does not raise a "user not found" error

## Actual behavior
Attempting to create a user sometimes results in a "user not found" error

## Steps to reproduce
```ruby
  def find_or_create_user(email, full_name)
    begin
      INTERCOM.users.find(email: email)
    rescue Intercom::ResourceNotFound
      INTERCOM.users.create(email: email, name: full_name) # error raised on this line
    end
  end
```

## Logs
```
app/worker.1:  4 TID-grysqqmz0 WARN: Intercom::ResourceNotFound: User Not Found 
app/worker.1:  4 TID-grysqqmz0 WARN: /app/vendor/bundle/ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/request.rb:175:in `raise_application_errors_on_failure' 
app/worker.1:  /app/vendor/bundle/ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/request.rb:114:in `parse_body' 
app/worker.1:  /app/vendor/bundle/ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/request.rb:77:in `block in execute' 
app/worker.1:  /app/vendor/ruby-2.5.5/lib/ruby/2.5.0/net/http.rb:910:in `start' 
app/worker.1:  /app/vendor/bundle/ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/request.rb:72:in `execute' 
app/worker.1:  /app/vendor/bundle/ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/client.rb:136:in `execute_request' 
app/worker.1:  /app/vendor/bundle/ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/client.rb:111:in `post' 
app/worker.1:  /app/vendor/bundle/ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/api_operations/save.rb:27:in `save' 
app/worker.1:  /app/vendor/bundle/ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/api_operations/save.rb:19:in `create' 
app/worker.1:  /app/app/workers/update_intercom_worker.rb:23:in `rescue in find_or_create_user' 
app/worker.1:  /app/app/workers/update_intercom_worker.rb:19:in `find_or_create_user' 
 ```

**Comment by theandrewykim** [comment]
@andrewhavens It looks like this may be more of an issue with the implementation of our API. Do you mind writing into our messenger at https://developers.intercom.com/reference - or emailing team@intercom.io? Our team of support engineers will be able to dig into this for you there!

**Comment by konalegi** [comment]
is there any updates? we still facing this issue.

**Comment by andrewhavens** [comment]
@konalegi You need to send an email to their support team in order to provide them with the details. My issue was only temporary and I haven't noticed it again, so for me, I'm assuming it's fixed. But if you're still having this problem you need to reach out to them so they have some real data to inspect.
