### ISSUE TITLE
Creating a note or tag for a contact causes a NoMethodError within NestedResource

### ISSUE THREAD

**Issue by goduchesne** [intercom/intercom-ruby#513]
## Version info
  - intercom-ruby version: 4.0.0
  - Ruby version: 2.6.5p114

## Expected behavior
The note or tag should be created for the contact.

## Actual behavior
`client` seems to be undefined within NestedResource and does not properly create the note or tag for the contact.

## Steps to reproduce
Note :
```ruby
intercom = Intercom::Client.new(token: ENV["INTERCOM_TOKEN"], api_version: "2.0")
contact = intercom.contacts.create(email: "email123@example.org", name: "John Doe")
contact.create_note(body: "This is a note")
```
Tag :
```ruby
intercom = Intercom::Client.new(token: ENV["INTERCOM_TOKEN"], api_version: "2.0")
contact = intercom.contacts.create(email: "email123@example.org", name: "John Doe")
tag = intercom.tags.tag(name: "tag name")
contact.add_tag(id: tag.id)
```

## Logs
```
Traceback (most recent call last):
       16: from bootsnap (1.4.5) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
       15: from bootsnap (1.4.5) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
       14: from bootsnap (1.4.5) lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
       13: from bootsnap (1.4.5) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
       12: from bootsnap (1.4.5) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
       11: from rails (b115cf9c967e) railties/lib/rails/commands.rb:18:in `<main>'
       10: from rails (b115cf9c967e) railties/lib/rails/command.rb:46:in `invoke'
        9: from rails (b115cf9c967e) railties/lib/rails/command/base.rb:69:in `perform'
        8: from thor (1.0.1) lib/thor.rb:392:in `dispatch'
        7: from thor (1.0.1) lib/thor/invocation.rb:127:in `invoke_command'
        6: from thor (1.0.1) lib/thor/command.rb:27:in `run'
        5: from rails (b115cf9c967e) railties/lib/rails/commands/console/console_command.rb:102:in `perform'
        4: from rails (b115cf9c967e) railties/lib/rails/commands/console/console_command.rb:19:in `start'
        3: from rails (b115cf9c967e) railties/lib/rails/commands/console/console_command.rb:70:in `start'
        2: from (irb):4
        1: from intercom (4.0.0) lib/intercom/api_operations/nested_resource.rb:30:in `block (2 levels) in nested_resource_methods'
NoMethodError (undefined method `post' for nil:NilClass)
```

**Comment by murtron** [comment]
Fixed in 4.0.1 - https://github.com/intercom/intercom-ruby/releases/tag/4.0.1. 

Sorry for the trouble @goduchesne. Feel free to reopen if you're still having issues.
