### ISSUE TITLE
Conflict between ApiOperations::NestedResource and Lib::DynamicAccessors (and/or Lib::DynamicAccessorsOnMethodMissing)

### ISSUE THREAD

**Issue by atcruice** [intercom/intercom-ruby#562]
## Version info
  - intercom-ruby version: 4.1.2
  - Ruby version: 2.6.6
  - Intercom client API version: 2.2

## Expected behavior
`Intercom::Contact#tags` always returns an enumerable collection proxy.

## Actual behavior
Through some unexpected series of events (I'm still narrowing it down), `Intercom::Contact#tags` is being overridden by the setter and getter created by `Lib::DynamicAccessors`. Instead of `#tags` creating an API request, it simply tries to check the value of an instance variable `@tags` which is `nil`. This manifests as various `NoMethodError` exceptions:
```ruby
contact.tags.map { … }
# => NoMethodError: undefined method `map' for nil:NilClass

contact.tags.select { … }
# => NoMethodError: private method `select' called for nil:NilClass
```

## Steps to reproduce
I have an order dependant, reproducible test failure that I'm using to investigate this issue. I've been patching `Intercom::Contact` to study the behaviour.
```ruby
module Intercom
  class Contact
    # added to observe when #tags and #tags= are defined
    def self.method_added(method_name)
      return unless %i[tags tags=].include?(method_name)

      puts
      puts "Adding #{method_name.inspect}"
      puts caller(0...10)
    end

    include Traits::IncrementableAttributes
    include Traits::ApiResource
    include ApiOperations::NestedResource

    nested_resource_methods :tag, operations: %i[add delete list]
    nested_resource_methods :note, operations: %i[create list]
    nested_resource_methods :company, operations: %i[add delete list]
    nested_resource_methods :segment, operations: %i[list]

    # added to observe how a Contact object is mutated as
    # from_hash is a common point between initialize and from_response
    def from_hash(hash)
      puts
      puts "from_hash: #{hash.inspect}"
      puts caller(0...5)
      super
    end
```

At this stage I suspect the bug is related to:
1. the format of an API response
2. causing a failure of the `addressable_list?` check, https://github.com/intercom/intercom-ruby/blob/4.1.2/lib/intercom/traits/api_resource.rb#L75
3. causing `#tags=` (and also `#tags`) accessors to be dynamically defined, overriding the original definition from `nested_resource_methods`

I'm keen to see this issue resolved, and will continue digging. I'm more than happy to open a pull request with a fix if I can have someone in-the-know confirm I'm looking in the right direction.

## Logs
I've analysed our logs of background job executions (over 11k entries for the task encountering this error). Across 342 unique jobs:
- only 26% did **not** encounter the issue at all
- so it's causing failure in 74% of job attempts
- only 90% of jobs had successfully completed at the time of analysis, these jobs retry and eventually succeed, but we usually have approximately 30 of these jobs in the retry queue at any time

**Comment by atcruice** [comment]
I've been able to isolate a minimal, reproducible example, and identify the API action causing it.
_given the patches to `Intercom::Contact` outlined above_
```ruby
#!/usr/bin/env ruby
# example repro script asdf.rb

require "intercom"

contact = Intercom::Contact.new

puts
puts "Intercom::Contact#tags source location"
puts contact.method(:tags).source_location

hash = {
  "type" => "company",
  "tags" => {"type" => "tag.list", "tags" => []},
}

contact.from_hash(hash)

puts
puts "Intercom::Contact#tags source location"
puts contact.method(:tags).source_location
```

## Output
```
$ bundle exec ./asdf.rb

Adding :tags
intercom-4.1.2/lib/intercom/contact.rb:14:in `method_added'
intercom-4.1.2/lib/intercom/api_operations/nested_resource.rb:49:in `define_method'
intercom-4.1.2/lib/intercom/api_operations/nested_resource.rb:49:in `block in nested_resource_methods'
intercom-4.1.2/lib/intercom/api_operations/nested_resource.rb:25:in `each'
intercom-4.1.2/lib/intercom/api_operations/nested_resource.rb:25:in `nested_resource_methods'
intercom-4.1.2/lib/intercom/contact.rb:21:in `<class:Contact>'
intercom-4.1.2/lib/intercom/contact.rb:8:in `<module:Intercom>'
intercom-4.1.2/lib/intercom/contact.rb:7:in `<top (required)>'
intercom-4.1.2/lib/intercom.rb:26:in `require'
intercom-4.1.2/lib/intercom.rb:26:in `<top (required)>'

Intercom::Contact#tags source location
intercom-4.1.2/lib/intercom/api_operations/nested_resource.rb
49

from_hash: {"type"=>"company", "tags"=>{"type"=>"tag.list", "tags"=>[]}}
/Users/atcruice/code/fivegoodfriends/fivegoodfriends/asdf.rb:16:in `<top (required)>'

Adding :tags=
intercom-4.1.2/lib/intercom/contact.rb:14:in `method_added'
(eval):2:in `define_standard_accessors'
intercom-4.1.2/lib/intercom/lib/dynamic_accessors.rb:45:in `class_eval'
intercom-4.1.2/lib/intercom/lib/dynamic_accessors.rb:45:in `define_standard_accessors'
intercom-4.1.2/lib/intercom/lib/dynamic_accessors.rb:14:in `define_accessors'
intercom-4.1.2/lib/intercom/traits/api_resource.rb:77:in `initialize_property'
intercom-4.1.2/lib/intercom/traits/api_resource.rb:32:in `block in from_hash'
intercom-4.1.2/lib/intercom/traits/api_resource.rb:31:in `each'
intercom-4.1.2/lib/intercom/traits/api_resource.rb:31:in `from_hash'
intercom-4.1.2/lib/intercom/contact.rb:33:in `from_hash'

Adding :tags
intercom-4.1.2/lib/intercom/contact.rb:14:in `method_added'
(eval):6:in `define_standard_accessors'
intercom-4.1.2/lib/intercom/lib/dynamic_accessors.rb:45:in `class_eval'
intercom-4.1.2/lib/intercom/lib/dynamic_accessors.rb:45:in `define_standard_accessors'
intercom-4.1.2/lib/intercom/lib/dynamic_accessors.rb:14:in `define_accessors'
intercom-4.1.2/lib/intercom/traits/api_resource.rb:77:in `initialize_property'
intercom-4.1.2/lib/intercom/traits/api_resource.rb:32:in `block in from_hash'
intercom-4.1.2/lib/intercom/traits/api_resource.rb:31:in `each'
intercom-4.1.2/lib/intercom/traits/api_resource.rb:31:in `from_hash'
intercom-4.1.2/lib/intercom/contact.rb:33:in `from_hash'

Intercom::Contact#tags source location
(eval)
6
```
From the output you can see the original expected definition of `Intercom::Contact#tags` from `ApiOperations::NestedResource`. Then after feeding that hash into `#from_hash` the accessors for `#tags=` and `#tags` are redefined by `Lib::DynamicAccessors` because the tags data value has the format `{"type" => "tags.list"}` instead of the format expected by the `#addressable_list?` check `{"type" => "list"}`, https://github.com/intercom/intercom-ruby/blob/4.1.2/lib/intercom/traits/api_resource.rb#L84

This issue occurs when you call `Intercom::Contact#add_company`. The response has the unexpected format and causes the redefinition of `Intercom::Contact#tags`.

```ruby
contact = intercom.contacts.find(id: …)
contact.tags.map(&:name) # works as expected
contact.add_company(id: …)
contact.tags.map(&:name) # now broken
```

**Comment by atcruice** [comment]
The workaround I have at the moment is to just call `load "intercom/contact"` before reaching for `Intercom::Contact#tags`. This ensures the redefinition according to `ApiOperations::NestedResource`.

**Comment by atcruice** [comment]
Apparently resolved by https://github.com/intercom/intercom-ruby/pull/566.
